# Generated by Django 5.2.16 on 2026-07-10 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='學校名稱')),
                ('academic_year', models.CharField(blank=True, max_length=16, verbose_name='目前學年度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '學校設定',
                'verbose_name_plural': '學校設定',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='學號')),
                ('full_name', models.CharField(max_length=100, verbose_name='學生姓名')),
                ('gender', models.CharField(choices=[('unspecified', '未填'), ('female', '女'), ('male', '男'), ('other', '其他／自述')], default='unspecified', max_length=16, verbose_name='性別')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年級')),
                ('class_name', models.CharField(blank=True, max_length=32, verbose_name='班別')),
                ('seat_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='座號')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='學生 Email')),
                ('home_phone', models.CharField(blank=True, max_length=32, verbose_name='住家電話')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住址')),
                ('is_active', models.BooleanField(default=True, verbose_name='在學／啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '學生',
                'verbose_name_plural': '學生',
                'ordering': ['grade', 'class_name', 'seat_number', 'full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '系統使用者', 'verbose_name_plural': '系統使用者'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='已核准使用'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', '技術系統管理員'), ('special_education_lead', '特教組長／主管'), ('case_manager', '個管教師'), ('course_teacher', '任課教師'), ('homeroom_teacher', '班級導師'), ('viewer', '閱覽者')], default='viewer', max_length=32, verbose_name='業務角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Google email'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=32, verbose_name='稱謂')),
                ('full_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('organization_or_school', models.CharField(blank=True, max_length=150, verbose_name='服務機關／就讀學校')),
                ('education_major', models.CharField(blank=True, max_length=150, verbose_name='畢業科系')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='專長')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='聯絡電話')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '家庭成員',
                'verbose_name_plural': '家庭成員',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('legal_guardian', '法定代理人'), ('father', '父親'), ('mother', '母親'), ('other', '其他')], default='legal_guardian', max_length=24, verbose_name='關係')),
                ('full_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone_work', models.CharField(blank=True, max_length=32, verbose_name='公司電話')),
                ('phone_mobile', models.CharField(blank=True, max_length=32, verbose_name='手機')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要聯絡人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '法定代理人',
                'verbose_name_plural': '法定代理人',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='one_primary_guardian_per_student')],
            },
        ),
        migrations.CreateModel(
            name='StudentStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('case_manager', '個管教師'), ('course_teacher', '任課教師'), ('homeroom_teacher', '班級導師'), ('viewer', '閱覽者')], max_length=24, verbose_name='指派角色')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to=settings.AUTH_USER_MODEL, verbose_name='教師／人員')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生教師指派',
                'verbose_name_plural': '學生教師指派',
                'constraints': [models.UniqueConstraint(fields=('student', 'staff', 'role', 'start_date'), name='unique_student_staff_role_start_date')],
            },
        ),
    ]
