# Generated by Django 5.2.16 on 2026-07-10 11:42

import accounts.models
import accounts.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schoolsetting_student_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('course_plan', '課程計畫'), ('timetable', '課表')], max_length=24, verbose_name='文件類型')),
                ('title', models.CharField(max_length=150, verbose_name='文件標題')),
                ('academic_year', models.CharField(blank=True, max_length=16, verbose_name='學年度')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='學期')),
                ('document_file', models.FileField(upload_to=accounts.models.private_document_upload_to, validators=[accounts.validators.validate_program_document], verbose_name='檔案')),
                ('original_filename', models.CharField(editable=False, max_length=255, verbose_name='原始檔名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '課程文件',
                'verbose_name_plural': '課程文件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
