# Generated by Django 5.2.16 on 2026-07-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_programdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.CharField(blank=True, max_length=64, verbose_name='獲獎日期')),
                ('activity_name', models.CharField(blank=True, max_length=255, verbose_name='競賽／活動名稱')),
                ('organizer', models.CharField(blank=True, max_length=255, verbose_name='主辦單位')),
                ('award', models.CharField(blank=True, max_length=255, verbose_name='獎項')),
                ('award_type', models.CharField(blank=True, max_length=100, verbose_name='得獎類型')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_records', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '得獎紀錄',
                'verbose_name_plural': '得獎紀錄',
            },
        ),
        migrations.CreateModel(
            name='InitialIGPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(default=dict, editable=False, verbose_name='原始完整回覆')),
                ('source_submitted_at', models.CharField(blank=True, max_length=64, verbose_name='原始填表時間')),
                ('source_email', models.CharField(blank=True, max_length=254, verbose_name='原始填表 Email')),
                ('has_multiple_special_education_needs', models.TextField(blank=True, verbose_name='是否有雙重特教需求')),
                ('additional_family_notes', models.TextField(blank=True, verbose_name='其他家庭成員說明')),
                ('family_culture', models.TextField(blank=True, verbose_name='家庭文化特質')),
                ('primary_caregiver', models.TextField(blank=True, verbose_name='主要照顧者')),
                ('learning_supporter', models.TextField(blank=True, verbose_name='主要協助學習者')),
                ('household_economy', models.TextField(blank=True, verbose_name='家庭經濟狀況')),
                ('caregiving_style', models.TextField(blank=True, verbose_name='照顧者管教態度')),
                ('family_interaction', models.TextField(blank=True, verbose_name='與家人互動情形')),
                ('math_aptitude_score', models.CharField(blank=True, max_length=64, verbose_name='數學性向測驗分數')),
                ('science_aptitude_score', models.CharField(blank=True, max_length=64, verbose_name='自然性向測驗分數')),
                ('math_practical_t_score', models.CharField(blank=True, max_length=64, verbose_name='數學實作評量 T 分數')),
                ('science_practical_t_score', models.CharField(blank=True, max_length=64, verbose_name='自然實作評量 T 分數')),
                ('science_interests', models.TextField(blank=True, verbose_name='科學興趣')),
                ('arts_interests', models.TextField(blank=True, verbose_name='人文與藝術興趣')),
                ('other_interests', models.TextField(blank=True, verbose_name='其他興趣')),
                ('other_awards_notes', models.TextField(blank=True, verbose_name='其他得獎紀錄')),
                ('completed_by', models.CharField(blank=True, max_length=100, verbose_name='填寫者')),
                ('cognitive_strengths', models.TextField(blank=True, verbose_name='認知優勢特質')),
                ('emotional_strengths', models.TextField(blank=True, verbose_name='情意優勢特質')),
                ('academic_strengths', models.TextField(blank=True, verbose_name='學科優勢能力')),
                ('cognitive_needs', models.TextField(blank=True, verbose_name='認知弱勢特質')),
                ('emotional_needs', models.TextField(blank=True, verbose_name='情意弱勢特質')),
                ('academic_needs', models.TextField(blank=True, verbose_name='學科弱勢能力')),
                ('notes', models.TextField(blank=True, verbose_name='其他補充說明事項')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_igp_profile', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '初始 IGP 概況',
                'verbose_name_plural': '初始 IGP 概況',
            },
        ),
    ]
