# Generated by Django 5.2.16 on 2026-07-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_teachers_for_existing_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Teacher = apps.get_model("accounts", "Teacher")
    Assignment = apps.get_model("accounts", "StudentStaffAssignment")
    eligible_roles = {"case_manager", "course_teacher", "homeroom_teacher"}
    user_ids = set(User.objects.filter(role__in=eligible_roles).values_list("id", flat=True))
    user_ids.update(Assignment.objects.values_list("staff_id", flat=True))

    for user in User.objects.filter(id__in=user_ids):
        role = user.role
        if role not in eligible_roles:
            role = Assignment.objects.filter(staff_id=user.id).values_list("role", flat=True).first() or "course_teacher"
        full_name = " ".join(part for part in (user.first_name, user.last_name) if part).strip() or user.username
        Teacher.objects.create(id=user.id, full_name=full_name, role=role, account_id=user.id)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_awardrecord_initialigpprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150, verbose_name="\u6559\u5e2b\u59d3\u540d")),
                ("role", models.CharField(choices=[("case_manager", "\u500b\u7ba1\u6559\u5e2b"), ("course_teacher", "\u4efb\u8ab2\u6559\u5e2b"), ("homeroom_teacher", "\u73ed\u7d1a\u5c0e\u5e2b")], max_length=32, verbose_name="\u6559\u5e2b\u89d2\u8272")),
                ("is_active", models.BooleanField(default=True, verbose_name="\u555f\u7528")),
                ("account", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teacher_profile", to=settings.AUTH_USER_MODEL, verbose_name="\u767b\u5165\u5e33\u865f")),
            ],
            options={
                "verbose_name": "\u6559\u5e2b",
                "verbose_name_plural": "\u6559\u5e2b",
                "ordering": ["full_name", "id"],
            },
        ),
        migrations.RunPython(create_teachers_for_existing_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="studentstaffassignment",
            name="staff",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="student_assignments", to="accounts.teacher", verbose_name="\u6559\u5e2b\uff0f\u4eba\u54e1"),
        ),
    ]
