# Generated by Django 5.2.16 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_teacher_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="has_multiple_special_education_needs",
            field=models.BooleanField(default=False, verbose_name="\u96d9\u91cd\u7279\u6559\u9700\u6c42"),
        ),
    ]
