# Generated by Django 5.2.16 on 2026-07-11

from django.db import migrations


def move_multiple_needs_to_student(apps, schema_editor):
    Profile = apps.get_model("accounts", "InitialIGPProfile")
    Student = apps.get_model("accounts", "Student")
    yes_values = {"是", "yes", "true", "1", "有"}
    for profile in Profile.objects.exclude(has_multiple_special_education_needs=""):
        if str(profile.has_multiple_special_education_needs).strip().lower() in yes_values:
            Student.objects.filter(pk=profile.student_id).update(has_multiple_special_education_needs=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_student_has_multiple_special_education_needs"),
    ]

    operations = [
        migrations.RunPython(move_multiple_needs_to_student, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="initialigpprofile",
            name="has_multiple_special_education_needs",
        ),
    ]
