# Generated by Django 5.2.16 on 2026-07-11 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_initialigpprofile_has_multiple_special_education_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='課程名稱')),
                ('goals', models.TextField(verbose_name='課程目標')),
                ('activities', models.TextField(blank=True, verbose_name='學習活動／調整')),
            ],
            options={
                'verbose_name': '課程計畫',
                'verbose_name_plural': '課程計畫',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='評量名稱')),
                ('assessed_on', models.DateField(blank=True, null=True, verbose_name='評量日期')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='結果／分數')),
                ('notes', models.TextField(blank=True, verbose_name='說明')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '評量紀錄',
                'verbose_name_plural': '評量紀錄',
                'ordering': ['-assessed_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IGPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=16, verbose_name='學年度')),
                ('overall_goal', models.TextField(verbose_name='年度目標')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igp_plans', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': 'IGP 年度計畫',
                'verbose_name_plural': 'IGP 年度計畫',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='領域')),
                ('detail', models.CharField(max_length=255, verbose_name='興趣內容')),
                ('notes', models.TextField(blank=True, verbose_name='補充說明')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '興趣',
                'verbose_name_plural': '興趣',
                'ordering': ['category', 'detail'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='記錄日期')),
                ('outcome', models.TextField(verbose_name='學習成果')),
                ('reflection', models.TextField(blank=True, verbose_name='檢核與調整')),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='accounts.courseplan', verbose_name='課程計畫')),
            ],
            options={
                'verbose_name': '學習成果',
                'verbose_name_plural': '學習成果',
                'ordering': ['-recorded_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '第一學期'), (2, '第二學期')], verbose_name='學期')),
                ('goals', models.TextField(verbose_name='學期目標')),
                ('strategies', models.TextField(blank=True, verbose_name='執行策略')),
                ('igp_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='accounts.igpplan', verbose_name='IGP 年度計畫')),
            ],
            options={
                'verbose_name': '學期計畫',
                'verbose_name_plural': '學期計畫',
                'ordering': ['igp_plan', 'semester'],
            },
        ),
        migrations.AddField(
            model_name='courseplan',
            name='semester_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plans', to='accounts.semesterplan', verbose_name='學期計畫'),
        ),
        migrations.AddConstraint(
            model_name='igpplan',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_igp_plan_per_student_year'),
        ),
        migrations.AddConstraint(
            model_name='semesterplan',
            constraint=models.UniqueConstraint(fields=('igp_plan', 'semester'), name='unique_semester_plan_per_igp'),
        ),
    ]
