# Generated by Django 5.2.16 on 2026-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_courseplan_assessment_igpplan_interest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentstaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_active', True), ('role', 'case_manager')), fields=('student',), name='one_current_case_manager_per_student'),
        ),
    ]
