# Generated by Django 5.2.16 on 2026-07-12 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentstaffassignment_one_current_case_manager_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='affective_support',
            field=models.TextField(blank=True, verbose_name='情意輔導方面'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='cognitive_adjustments',
            field=models.TextField(blank=True, verbose_name='認知教學方面'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='learning_domains',
            field=models.TextField(blank=True, verbose_name='領域學習課程'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='skill_training',
            field=models.TextField(blank=True, verbose_name='技能培訓方面'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='special_needs_courses',
            field=models.TextField(blank=True, verbose_name='特殊需求課程'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_plans', to='accounts.teacher', verbose_name='授課教師'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='academic_needs',
            field=models.TextField(blank=True, verbose_name='學科弱勢能力'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='academic_strengths',
            field=models.TextField(blank=True, verbose_name='學科優勢能力'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='cognitive_needs',
            field=models.TextField(blank=True, verbose_name='認知弱勢特質'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='cognitive_strengths',
            field=models.TextField(blank=True, verbose_name='認知優勢特質'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='emotional_needs',
            field=models.TextField(blank=True, verbose_name='情意弱勢特質'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='emotional_strengths',
            field=models.TextField(blank=True, verbose_name='情意優勢特質'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='learning_strategies',
            field=models.TextField(blank=True, verbose_name='學習策略'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='qualitative_analysis',
            field=models.TextField(blank=True, verbose_name='優弱勢能力綜合評析（質性描述）'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='course_needs_assessment',
            field=models.TextField(blank=True, verbose_name='課程需求評估'),
        ),
        migrations.CreateModel(
            name='LearningPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='學習表現')),
                ('adjustment', models.TextField(blank=True, verbose_name='學習表現調整')),
                ('assessment_methods', models.TextField(blank=True, verbose_name='評量方式')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='項次')),
                ('course_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_performances', to='accounts.courseplan', verbose_name='課程計畫')),
            ],
            options={
                'verbose_name': '學習表現條目',
                'verbose_name_plural': '學習表現條目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '○1 再努力'), (2, '○2 尚可'), (3, '○3 良好'), (4, '○4 優異')], verbose_name='教師評分')),
                ('notes', models.TextField(blank=True, verbose_name='評語')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='評分教師帳號')),
                ('learning_performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.learningperformance', verbose_name='學習表現')),
            ],
            options={
                'verbose_name': '學習成果評分',
                'verbose_name_plural': '學習成果評分',
            },
        ),
    ]
