# Generated by Django 5.2.16 on 2026-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_move_strengths_to_annual_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterplan',
            name='learning_domains',
            field=models.TextField(blank=True, verbose_name='領域學習課程'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='special_needs_courses',
            field=models.TextField(blank=True, verbose_name='特殊需求課程'),
        ),
    ]
