# Generated by Django 5.2.16 on 2026-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_semesterplan_learning_domains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningperformance',
            name='description',
            field=models.TextField(blank=True, verbose_name='學習表現'),
        ),
        migrations.AlterField(
            model_name='learningperformance',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='項次'),
        ),
    ]
