# Generated by Django 5.2.16 on 2026-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_learningperformance_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='目前修課'),
        ),
    ]
