# Generated by Django 5.2.16 on 2026-07-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_courseplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='課程範本'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_plans', to='accounts.courseplan', verbose_name='課程範本'),
        ),
    ]
