# Generated by Django 5.2.16 on 2026-07-15 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_populate_course_plan_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='發生時間')),
                ('event_type', models.CharField(choices=[('counseling_created', '建立輔導紀錄'), ('counseling_submitted', '送審輔導紀錄'), ('counseling_returned', '退回輔導紀錄'), ('counseling_reviewed', '審核輔導紀錄'), ('counseling_locked', '鎖定輔導紀錄'), ('user_permission_changed', '帳號權限變更'), ('assignment_changed', '學生教師指派變更'), ('student_import_applied', '匯入學生資料'), ('document_uploaded', '上傳課程文件'), ('document_deleted', '刪除課程文件')], max_length=32, verbose_name='事件類型')),
                ('target_model', models.CharField(max_length=100, verbose_name='目標類型')),
                ('target_pk', models.CharField(max_length=64, verbose_name='目標識別')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '稽核事件',
                'verbose_name_plural': '稽核事件',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CounselingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=16, verbose_name='學年度')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='紀錄日期')),
                ('subject', models.CharField(max_length=150, verbose_name='主題／類別')),
                ('content', models.TextField(verbose_name='輔導內容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已送審'), ('returned', '退回修正'), ('reviewed', '已審核'), ('locked', '已鎖定')], default='draft', max_length=16, verbose_name='狀態')),
                ('review_note', models.TextField(blank=True, verbose_name='審核意見')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='送審時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='鎖定時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_counseling_records', to=settings.AUTH_USER_MODEL, verbose_name='紀錄者')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_counseling_records', to=settings.AUTH_USER_MODEL, verbose_name='鎖定者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_counseling_records', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_records', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '輔導紀錄',
                'verbose_name_plural': '輔導紀錄',
                'ordering': ['-recorded_on', '-id'],
            },
        ),
    ]
