# Generated by Django 5.2.16 on 2026-07-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_counseling_record_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_documents', to='accounts.student', verbose_name='學生'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='document_type',
            field=models.CharField(choices=[('igp_plan', 'IGP 計畫'), ('course_plan', '課程計畫'), ('timetable', '課表')], max_length=24, verbose_name='文件類型'),
        ),
    ]
