# Generated by Django 5.2.16 on 2026-07-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_programdocument_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpplan',
            name='affective_analysis',
            field=models.TextField(blank=True, verbose_name='情意方面'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='strength_language',
            field=models.TextField(blank=True, verbose_name='優勢－學習領域（語文）'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='strength_math_science',
            field=models.TextField(blank=True, verbose_name='優勢－學習領域（數理）'),
        ),
        migrations.AddField(
            model_name='igpplan',
            name='weakness_analysis',
            field=models.TextField(blank=True, verbose_name='劣勢'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='class_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='班級'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年級'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='school_name',
            field=models.CharField(default='平興國中', max_length=150, verbose_name='就讀學校'),
        ),
        migrations.AddField(
            model_name='student',
            name='gifted_categories',
            field=models.TextField(blank=True, verbose_name='資優類別'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='document_type',
            field=models.CharField(choices=[('igp_plan', 'IGP 計畫'), ('igp_meeting', 'IGP 會議紀錄'), ('course_plan', '課程計畫'), ('timetable', '課表')], max_length=24, verbose_name='文件類型'),
        ),
        migrations.CreateModel(
            name='AssessmentSubscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='分量表')),
                ('score', models.CharField(max_length=100, verbose_name='分量成績')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscales', to='accounts.assessment', verbose_name='評量紀錄')),
            ],
            options={
                'verbose_name': '評量分量表',
                'verbose_name_plural': '評量分量表',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IGPMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '第一學期'), (2, '第二學期')], verbose_name='學期')),
                ('meeting_type', models.CharField(choices=[('initial', '期初會議'), ('final', '期末會議')], max_length=16, verbose_name='會議類型')),
                ('meeting_date', models.DateField(verbose_name='會議日期')),
                ('meeting_time', models.TimeField(blank=True, null=True, verbose_name='時間')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='地點')),
                ('recorder', models.CharField(blank=True, max_length=100, verbose_name='記錄者')),
                ('attendees', models.TextField(blank=True, verbose_name='與會人員／簽到')),
                ('minutes', models.TextField(blank=True, verbose_name='會議紀錄')),
                ('igp_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.igpplan', verbose_name='IGP 年度計畫')),
            ],
            options={
                'verbose_name': 'IGP 會議紀錄',
                'verbose_name_plural': 'IGP 會議紀錄',
                'ordering': ['-meeting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('needs_description', models.TextField(blank=True, verbose_name='評估需求說明')),
                ('result_summary', models.TextField(blank=True, verbose_name='評估結果概要敘述')),
                ('recorder', models.CharField(blank=True, max_length=100, verbose_name='記錄人員')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_review_records', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '重新安置紀錄',
                'verbose_name_plural': '重新安置紀錄',
                'ordering': ['recorded_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationTransitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('grades_3_4', '3-4年級'), ('grades_5_6', '5-6年級'), ('junior_high', '國中')], max_length=24, verbose_name='階段')),
                ('school_name', models.CharField(blank=True, max_length=150, verbose_name='校名')),
                ('class_name', models.CharField(blank=True, max_length=32, verbose_name='班級')),
                ('homeroom_teacher', models.CharField(blank=True, max_length=100, verbose_name='普通班導師')),
                ('gifted_case_manager', models.CharField(blank=True, max_length=100, verbose_name='資優教育個管教師')),
                ('service_types', models.TextField(blank=True, verbose_name='服務類型')),
                ('other_service', models.CharField(blank=True, max_length=255, verbose_name='其他服務說明')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_transition_records', to='accounts.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '教育轉銜紀錄',
                'verbose_name_plural': '教育轉銜紀錄',
                'ordering': ['stage', 'id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'stage'), name='unique_education_transition_stage_per_student')],
            },
        ),
    ]
